#spring.datasource.url=jdbc:postgresql://localhost:5432/RESTPOC2
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=Sumitraj
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#server.port=9090 //server changing

server:
port: 9090
spring:
datasource:
driverClassName: org.postgresql.Driver
password: Sumitraj
url: jdbc:postgresql://localhost:5432/RESTPOC2
username: postgres
jpa:
database-platform: org.hibernate.dialect.PostgreSQLDialect
hibernate:
ddl-auto: update

